# Generated by Django 4.1.5 on 2023-01-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=70)),
                ('replace_word', models.CharField(max_length=70)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(max_length=50)),
                ('order_number', models.CharField(max_length=50)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
