# Generated by Django 4.1.5 on 2025-08-07 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_api', '0002_tracking_tracking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='tracking_id',
        ),
    ]
