# Generated by Django 4.1.5 on 2025-08-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_api', '0003_remove_tracking_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
